version: '3'
services:
  db:
    image: postgres:12-alpine
    container_name: ciaoestrela-db
    env_file:
      - db.env
    networks:
      - ciaoestrela

  api:
    image: tjlaekem/ciaoestrela-api:latest
    build: .
    container_name: ciaoestrela-api
    env_file:
      - api.env
    networks:
      - ciaoestrela
    links:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

networks:
  ciaoestrela:
