# Generated by Django 3.0.3 on 2020-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='pin_image',
            new_name='image',
        ),
    ]
