# Generated by Django 3.0.3 on 2020-05-27 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_auto_20200518_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pins.Image'),
        ),
    ]
