version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.8

  publisher:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  install:
    executor: python
    steps:
      - checkout
      - run:
          name: venv and install
          command: |
            python3.8 -m venv venv
            . venv/bin/activate
            make install
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - venv 

  lint:
    executor: python
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: venv and lint
          command: |
            . venv/bin/activate
            make lint

  test:
    executor: python
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: venv and test
          command: |
            . venv/bin/activate
            make test

  build_image:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build and tag
          command: docker build . -t tjlaekem/ciaoestrela-api:latest
      - run:
          name: save image
          command: docker save -o image.tar tjlaekem/ciaoestrela-api:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish_image:
    executor: publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: load image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: login to docker hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u tjlaekem --password-stdin
      - run:
          name: publish image
          command: docker push tjlaekem/ciaoestrela-api:latest

  deploy_image:
    executor: publisher
    steps:
      - add_ssh_keys:
          fingerprints:
            - "19:80:b0:e2:2f:d6:c6:3d:f7:e2:3b:b5:1f:5e:e2:62"
      - run:
          name: deploy to vm
          command: ssh -o "StrictHostKeyChecking no" tjlaekem@35.208.62.116 "docker-compose pull && docker-compose stop && docker-compose up -d"

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build_image
      - publish_image:
          requires:
            - lint
            - test
            - build_image
      - deploy_image:
          requires:
            - publish_image
