version: 3
jobs:
  install:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: python3.8 -m venv venv
      - run: source venv/bin/activate
      - run: make install
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - venv 

  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: make lint

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run: make test

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
