# Generated by Django 3.0.3 on 2020-06-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('orders', '0020_auto_20200602_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.Model')),
                ('cost', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('ideas', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cards', to='orders.Order')),
                ('paper', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.PaperType')),
            ],
            bases=('utils.model',),
        ),
    ]
