# Generated by Django 3.0.3 on 2020-06-02 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200602_2259'),
        ('custom_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcard',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cards', to='orders.Order'),
        ),
    ]
