# Generated by Django 3.0.3 on 2020-06-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
