# Generated by Django 3.0.3 on 2020-06-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_seed_paper_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_image',
            new_name='image',
        ),
    ]
