# Generated by Django 3.0.3 on 2020-06-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200606_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='paper',
        ),
    ]
