# Generated by Django 3.0.3 on 2020-06-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_paper'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cards.PaperType'),
        ),
    ]
