# Generated by Django 3.0.2 on 2020-02-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcard',
            name='paper',
            field=models.TextField(null=True),
        ),
    ]
