# Generated by Django 3.0.2 on 2020-02-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_seed_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcard',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.PaperType'),
        ),
    ]
