# Generated by Django 3.0.3 on 2020-05-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200503_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
