# Generated by Django 3.0.3 on 2020-06-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcard',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='custom_cards', to='orders.Order'),
        ),
    ]
