# Generated by Django 3.0.3 on 2020-06-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_auto_20200527_0038'),
        ('orders', '0015_customcard_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pins',
            field=models.ManyToManyField(default=None, to='pins.Pin'),
        ),
    ]
