# Generated by Django 3.0.3 on 2020-06-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200602_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcard',
            name='order',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='custom_cards', to='orders.Order'),
        ),
    ]
