# Generated by Django 3.0.3 on 2020-06-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200602_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcard',
            name='order_item',
        ),
        migrations.AddField(
            model_name='customcard',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
