# Generated by Django 3.0.3 on 2020-06-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200602_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcard',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customcard',
            name='paper',
        ),
    ]
