# Generated by Django 3.0.3 on 2020-06-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cards', '0003_auto_20200602_2318'),
        ('orders', '0020_auto_20200602_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCard',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_type',
        ),
        migrations.DeleteModel(
            name='PaperType',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
